# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  cardealerwebapi:
    image: cardealerwebapi
    build:
      context: .
      dockerfile: CarDealerWebAPI/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - sqlserver
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
