// <auto-generated />
using CarDealerAPIService.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarDealerAPIService.App.Migrations
{
    [DbContext(typeof(CarDealerContext))]
    [Migration("20210605061832_initMigration")]
    partial class initMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarDealerAPIService.App.models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MarketValue")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VinNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VehicleInventory");

                    b.HasData(
                        new
                        {
                            Id = 1050,
                            Make = "Tesla",
                            MarketValue = 51,
                            Model = "T",
                            VinNumber = "1233asd",
                            Year = 210
                        },
                        new
                        {
                            Id = 4022,
                            Make = "Tesla",
                            MarketValue = 25,
                            Model = "A",
                            VinNumber = "1223a2d",
                            Year = 2200
                        },
                        new
                        {
                            Id = 4041,
                            Make = "Tesla",
                            MarketValue = 35,
                            Model = "B",
                            VinNumber = "12333asd",
                            Year = 21200
                        },
                        new
                        {
                            Id = 1045,
                            Make = "Toyota",
                            MarketValue = 45,
                            Model = "Camry",
                            VinNumber = "123asd",
                            Year = 21010
                        },
                        new
                        {
                            Id = 3141,
                            Make = "Tesla",
                            MarketValue = 55,
                            Model = "T",
                            VinNumber = "12gg3a234sd",
                            Year = 52100
                        },
                        new
                        {
                            Id = 2021,
                            Make = "Car",
                            MarketValue = 52,
                            Model = "a",
                            VinNumber = "12d3asd",
                            Year = 21020
                        },
                        new
                        {
                            Id = 2042,
                            Make = "Ford",
                            MarketValue = 15,
                            Model = "T",
                            VinNumber = "123fasd",
                            Year = 25100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
