name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Release
      run: dotnet publish -c release
    - uses: actions/upload-artifact@v2
      with:
        name: CarDealerApiService.App Artifact
        path: CarDealerApiService.App/bin/Release
    - uses: actions/upload-artifact@v2
      with:
        name: CarDealerWebAPI Artifact
        path: CarDealerWebAPI/bin/Release
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Install Buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
    - name: Build
      run: docker compose build
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{secrets.DOCKERHUB_USERNAME}}/cardealerwebapiimage:latest
        file: CarDealerWebAPI/Dockerfile

