name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Release
      run: dotnet publish -c release
    - uses: actions/upload-artifact@v2
      with:
        name: CarDealerApiService.App Artifact
        path: CarDealerWebAPI.App/bin/Release
    - uses: actions/upload-artifact@v2
      with:
        name: CarDealerWebAPI Artifact
        path: CarDealerWebAPI/bin/Release

